my_car_site/cars/urls.py
from django.urls import path
from . import views

app_name = 'cars'

urlpatterns = [
    #domain.com/cars/
    path('list/',views.list,name='list'),
    path('add/',views.add,name='add'),
    path('delete/',views.delete,name='delete'),

]

my_car_site/my_car_site/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cars/',include('cars.urls'))
]

my_car_site/cars/models.py
from pyexpat import model
from django.db import models

# Create your models here.
class Car(models.Model):
    brand = models.CharField(max_length= 30)
    year = models.IntegerField()

    def __str__(self):
        return f"car is {self.brand} {self.year}"

my_car_site/cars/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from . import models

# Create your views here.
def list(request):
    all_cars = models.Car.objects.all()
    #we need the line above to be dictoinary to be able to send it 
    context = {'all_cars': all_cars}
    return render(request,'cars/list.html', context= context)

def add(request):
    if request.POST:
        brand = request.POST['brand']
        year = int(request.POST['year'])
        models.Car.objects.create(brand = brand , year = year)
        #if user submitted a new car --> list.html
        return redirect(reverse('cars:list'))
    else:
        return render(request,'cars/add.html')

def delete(request):
    if request.POST:
        #delte the car
        pk = request.POST['pk']
        try:
            models.Car.objects.get(pk=pk).delete()
            return redirect(reverse('cars:list'))

        except:
            print('pk not found')
            return redirect(reverse('cars:list'))
    else:
        return render(request,'cars/delete.html')

my_car_site/cars/templates/cars/add.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <h1>ADD.HTML</h1>
    <h2>add a new car to the database:</h2>
    <form action="" method="POST">
        {% csrf_token %}
        <div class="form-group">
            <label for="brand">brand:</label>
            <input class="form-control" type="text" id="brand" name="brand">
        </div>
        <div class="form-group">
            <label for="year">year:</label>
            <input class="form-control" type="text" id="year" name="year">
        </div>
        <input class='btn btn-primary' type="submit">


    </form>
</div>

{% endblock %}

my_car_site/cars/templates/cars/delete.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <h1>DELETE.HTML</h1>
    <h2>Enter PK to delete the car</h2>
    <form action="" method="POST">

        {% csrf_token %}
            <div class="form-group">
                <label for="pk">PK Number:</label>
                <input class="form-control" type="text" id="pk" name="pk">
            </div>
            <input class="btn btn-primary" type="submit">
    </form>
</div>
{% endblock %}

my_car_site/cars/templates/cars/list.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <h1>LIST.HTMl</h1>
        <ul>
            {% for car in all_cars %}
                <li>{{car}}</li>
            {% endfor %}
        </ul>
</div>

{% endblock %}

my_car_site/templates/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <title>Document</title>
</head>
<body>

    <!-- NAVBAR -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
              <a class="nav-link" href="{% url 'cars:list' %}">LIST</a>
              <a class="nav-link" href="{% url 'cars:add' %}">ADD</a>
              <a class="nav-link" href="{% url 'cars:delete' %}">DELETE</a>

            </div>
          </div>
        </div>
      </nav>
    {% block content %}
    {% endblock %}
    
</body>
</html>